// Code generated by go-genconstructor; DO NOT EDIT.

package example

import (
	"time"
)

func NewPerson(
	id string,
	name string,
) Person {
	return Person{
		id:        id,
		name:      name,
		createdAt: time.Now(),
	}
}

func NewPersonService(
	id string,
) *PersonService {
	return &PersonService{
		id: id,
	}
}

func NewArmedWarrior(
	id string,
	name string,
	armament string,
) ArmedWarrior {
	return ArmedWarrior{
		Person: Person{
			id:        id,
			name:      name,
			createdAt: time.Now(),
		},
		armament: armament,
	}
}
